entity/fish.py
=> cobaye_change

planet.py
fonction d'init_grid fonctionnel
=> fonction init_grid

entity/shark.py
Mise à jour de la classe Shark :
- héritage de classe Fish
- affichage émoji :shark: grâce à package emoji
- fonction move : déplacement prioritaire vers un poisson en appelant fonction eat(), ou déplacement aléatoire
- fonction eat : augmente l'énergie
=> update Shark class

interface/main_window.py, planet.py
ajout window main + gestion de chronon dans la fonction update
=> Feature planet

README.md, entity/fish.py
Modification de la classe fish en modifiant le constructeur 
- suppression de reproduction_time dans le constructeur 
- ajout de petit commentaire 
Petit ajout dans le Readme.md
=> Modification de fish et de readme

README.md, entity/fish.py
Petite modif Fish 
Modif Readme
=> Modification Fish et ReadME.md

entity/__init__.py, entity/fish.py, entity/shark.py, main.py, planet.py
- Mise à jour de Shark
- planet : Création méthodes new_fish, new_shark et is_valide_position
- début initialisation monde de test
=> Update shark + planet + main

interface/grid_view.py, interface/main_window.py
Ajout des chornon en dynamique.
Changement de taille 
+ test a enlever plus tard dans le main windows
=> ajout des chronon + changement de taille des icone + test

entity/__init__.py, entity/clown_fish.py, entity/fish.py, entity/shark.py, main.py, planet.py
- création Classe ClownFish, héritage de Fish
- Modification Fish pour devenir aussi parente de ClownFish
- modification Shark pour comportement
- modification planet.py pour comportement grid
- modification main.py pour simuler comportement des entités dans la console
=> feature: ajout classe ClownFish, correction grid et classes pour comportement

interface/grid_view.py, interface/main_window.py, main.py
ajouts des fonctionnalités données par sayana
=> Ajout Fonctionnalité sayana

entity/clown_fish.py, entity/shark.py, main.py, planet.py
Update comportement des entités + résolution des conflits
=> Feature aurelien2

interface/grid_view.py, interface/main_window.py, main.py
bugfix sur l'historique qui ne quitter pas avec la main window + bugfix sur la grille qui ne se mettais pas en pause ou reprend la grille
=> bugfix sur la mainwindow historique +grid pause start

README.md, main.py
petit changement readme et correction de petit bug
=> petit changement

entity/clown_fish.py, entity/shark.py, interface/main_window.py, main.py, planet.py, utils/config.py
Debug du déplacement des entités et retrait aléatoire pour priorité requin (bug lorsque les requins mangent les poissons)
=> Feature aurelien3

main.py, planet.py
=> peitit changement dans les imports

main.py, planet.py
Mise à jour de la boucle principale run_simulation pour utilisation dans l'interface
=> Update boucle run_simulation

entity/shark.py, interface/main_window.py, main.py, utils/config.py
mise a jour du main 
-Correction de bug avec historique si instant historique n'est pas lancé.
-implémentation de la mise a jour interface graphique et la simulation par chronon de l'algorithme pattern des poissons et des requins
=> animation + algo aurelien implémenté

interface/main_window.py
mise a jour des condition de fin de wator
-changement de la fonction update simulator dans main windows
=> mise a jour des condition de fin de wator

entity/clown_fish.py, entity/shark.py, planet.py, utils/config.py
- correction de la mort des requins (appel de is_alive était en dehors de la boucle de mouvement)
- ajout de la configuration des temps de reproduction dans config.py
=> Correction mort des requins + settings dans config.py

interface/grid_view.py, interface/main_window.py, utils/config.py
=> bug grille x y dans la grid_view

utils/config.py
=> config simulation 100 chronon
